#!/bin/bash


vsm="../vsm"


if ! [ -e "$vsm" ]; then
	echo vsm does not exist.
	exit 1;
fi


diff <(cat assgn.test | $vsm) assgn.right
if [ "$?" = 0 ];then
	echo -n "[assgn test]"
	echo -e "\033[32m ok \033[m"
else
	echo -n "[assgn test]"
	echo -e "\033[31m test failed. \033[m"
fi


diff <(cat calc.test | $vsm) calc.right
if [ "$?" = 0 ];then
	echo -n "[calc test]"
	echo -e "\033[32m ok \033[m"
else
	echo -n "[calc test]"
	echo -e "\033[31m test failed. \033[m"
fi
