#!/bin/bash


vsm="../vsm"


print_result() 
{
	if [ "$?" = 0 ];then
		echo -e "\033[32m ok \033[m"
	else
		echo -e "\033[31m test failed. \033[m"
	fi
}


if ! [ -e "$vsm" ]; then
	echo vsm does not exist.
	exit 1;
fi


echo -n "[assgn test]"
diff <($vsm -f assgn.test) assgn.right
print_result


echo -n "[calc test]"
diff <($vsm -f calc.test) calc.right
print_result


echo -n "[read test]"
diff <( printf "1\n2\n3\n" | $vsm -f read.test) <( printf "1\n2\n3\n")
print_result


echo -n "[ppmm test]"
diff <($vsm -f ppmm.test) ppmm.right
print_result

echo -n "[relop test]"
diff <($vsm -f relop.test) relop.right
print_result

echo -n "[ternary op test]"
diff <($vsm -f ternaryop.test) ternaryop.right
print_result

echo -n "[if test]"
diff <($vsm -f if.test) if.right
print_result


echo -n "[for test]"
diff <($vsm -f for.test) for.right
print_result

echo -n "[while test]"
diff <($vsm -f while.test) while.right
print_result

echo -n "[break test]"
diff <($vsm -f break.test) break.right
print_result


